spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123
    database: 0
    client-type: lettuce
    lettuce:
      pool:
        max-active: 16
        max-idle: 16
        max-wait: 5000
    datasource